# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/debanik/CPP_mobile_robots

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/debanik/CPP_mobile_robots

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/debanik/CPP_mobile_robots/CMakeFiles /home/debanik/CPP_mobile_robots/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/debanik/CPP_mobile_robots/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named basic_class

# Build rule for target.
basic_class: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basic_class
.PHONY : basic_class

# fast build rule for target.
basic_class/fast:
	$(MAKE) -f CMakeFiles/basic_class.dir/build.make CMakeFiles/basic_class.dir/build
.PHONY : basic_class/fast

#=============================================================================
# Target rules for targets named basic_lambda

# Build rule for target.
basic_lambda: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basic_lambda
.PHONY : basic_lambda

# fast build rule for target.
basic_lambda/fast:
	$(MAKE) -f CMakeFiles/basic_lambda.dir/build.make CMakeFiles/basic_lambda.dir/build
.PHONY : basic_lambda/fast

#=============================================================================
# Target rules for targets named A_star_algo_opt

# Build rule for target.
A_star_algo_opt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 A_star_algo_opt
.PHONY : A_star_algo_opt

# fast build rule for target.
A_star_algo_opt/fast:
	$(MAKE) -f CMakeFiles/A_star_algo_opt.dir/build.make CMakeFiles/A_star_algo_opt.dir/build
.PHONY : A_star_algo_opt/fast

#=============================================================================
# Target rules for targets named bfs

# Build rule for target.
bfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bfs
.PHONY : bfs

# fast build rule for target.
bfs/fast:
	$(MAKE) -f CMakeFiles/bfs.dir/build.make CMakeFiles/bfs.dir/build
.PHONY : bfs/fast

#=============================================================================
# Target rules for targets named bfs_opt

# Build rule for target.
bfs_opt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bfs_opt
.PHONY : bfs_opt

# fast build rule for target.
bfs_opt/fast:
	$(MAKE) -f CMakeFiles/bfs_opt.dir/build.make CMakeFiles/bfs_opt.dir/build
.PHONY : bfs_opt/fast

#=============================================================================
# Target rules for targets named basic_vector

# Build rule for target.
basic_vector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basic_vector
.PHONY : basic_vector

# fast build rule for target.
basic_vector/fast:
	$(MAKE) -f CMakeFiles/basic_vector.dir/build.make CMakeFiles/basic_vector.dir/build
.PHONY : basic_vector/fast

src/A_star_algo_opt.o: src/A_star_algo_opt.cpp.o

.PHONY : src/A_star_algo_opt.o

# target to build an object file
src/A_star_algo_opt.cpp.o:
	$(MAKE) -f CMakeFiles/A_star_algo_opt.dir/build.make CMakeFiles/A_star_algo_opt.dir/src/A_star_algo_opt.cpp.o
.PHONY : src/A_star_algo_opt.cpp.o

src/A_star_algo_opt.i: src/A_star_algo_opt.cpp.i

.PHONY : src/A_star_algo_opt.i

# target to preprocess a source file
src/A_star_algo_opt.cpp.i:
	$(MAKE) -f CMakeFiles/A_star_algo_opt.dir/build.make CMakeFiles/A_star_algo_opt.dir/src/A_star_algo_opt.cpp.i
.PHONY : src/A_star_algo_opt.cpp.i

src/A_star_algo_opt.s: src/A_star_algo_opt.cpp.s

.PHONY : src/A_star_algo_opt.s

# target to generate assembly for a file
src/A_star_algo_opt.cpp.s:
	$(MAKE) -f CMakeFiles/A_star_algo_opt.dir/build.make CMakeFiles/A_star_algo_opt.dir/src/A_star_algo_opt.cpp.s
.PHONY : src/A_star_algo_opt.cpp.s

src/basic_class.o: src/basic_class.cpp.o

.PHONY : src/basic_class.o

# target to build an object file
src/basic_class.cpp.o:
	$(MAKE) -f CMakeFiles/basic_class.dir/build.make CMakeFiles/basic_class.dir/src/basic_class.cpp.o
.PHONY : src/basic_class.cpp.o

src/basic_class.i: src/basic_class.cpp.i

.PHONY : src/basic_class.i

# target to preprocess a source file
src/basic_class.cpp.i:
	$(MAKE) -f CMakeFiles/basic_class.dir/build.make CMakeFiles/basic_class.dir/src/basic_class.cpp.i
.PHONY : src/basic_class.cpp.i

src/basic_class.s: src/basic_class.cpp.s

.PHONY : src/basic_class.s

# target to generate assembly for a file
src/basic_class.cpp.s:
	$(MAKE) -f CMakeFiles/basic_class.dir/build.make CMakeFiles/basic_class.dir/src/basic_class.cpp.s
.PHONY : src/basic_class.cpp.s

src/basic_lambda.o: src/basic_lambda.cpp.o

.PHONY : src/basic_lambda.o

# target to build an object file
src/basic_lambda.cpp.o:
	$(MAKE) -f CMakeFiles/basic_lambda.dir/build.make CMakeFiles/basic_lambda.dir/src/basic_lambda.cpp.o
.PHONY : src/basic_lambda.cpp.o

src/basic_lambda.i: src/basic_lambda.cpp.i

.PHONY : src/basic_lambda.i

# target to preprocess a source file
src/basic_lambda.cpp.i:
	$(MAKE) -f CMakeFiles/basic_lambda.dir/build.make CMakeFiles/basic_lambda.dir/src/basic_lambda.cpp.i
.PHONY : src/basic_lambda.cpp.i

src/basic_lambda.s: src/basic_lambda.cpp.s

.PHONY : src/basic_lambda.s

# target to generate assembly for a file
src/basic_lambda.cpp.s:
	$(MAKE) -f CMakeFiles/basic_lambda.dir/build.make CMakeFiles/basic_lambda.dir/src/basic_lambda.cpp.s
.PHONY : src/basic_lambda.cpp.s

src/basic_vector.o: src/basic_vector.cpp.o

.PHONY : src/basic_vector.o

# target to build an object file
src/basic_vector.cpp.o:
	$(MAKE) -f CMakeFiles/basic_vector.dir/build.make CMakeFiles/basic_vector.dir/src/basic_vector.cpp.o
.PHONY : src/basic_vector.cpp.o

src/basic_vector.i: src/basic_vector.cpp.i

.PHONY : src/basic_vector.i

# target to preprocess a source file
src/basic_vector.cpp.i:
	$(MAKE) -f CMakeFiles/basic_vector.dir/build.make CMakeFiles/basic_vector.dir/src/basic_vector.cpp.i
.PHONY : src/basic_vector.cpp.i

src/basic_vector.s: src/basic_vector.cpp.s

.PHONY : src/basic_vector.s

# target to generate assembly for a file
src/basic_vector.cpp.s:
	$(MAKE) -f CMakeFiles/basic_vector.dir/build.make CMakeFiles/basic_vector.dir/src/basic_vector.cpp.s
.PHONY : src/basic_vector.cpp.s

src/bfs.o: src/bfs.cpp.o

.PHONY : src/bfs.o

# target to build an object file
src/bfs.cpp.o:
	$(MAKE) -f CMakeFiles/bfs.dir/build.make CMakeFiles/bfs.dir/src/bfs.cpp.o
.PHONY : src/bfs.cpp.o

src/bfs.i: src/bfs.cpp.i

.PHONY : src/bfs.i

# target to preprocess a source file
src/bfs.cpp.i:
	$(MAKE) -f CMakeFiles/bfs.dir/build.make CMakeFiles/bfs.dir/src/bfs.cpp.i
.PHONY : src/bfs.cpp.i

src/bfs.s: src/bfs.cpp.s

.PHONY : src/bfs.s

# target to generate assembly for a file
src/bfs.cpp.s:
	$(MAKE) -f CMakeFiles/bfs.dir/build.make CMakeFiles/bfs.dir/src/bfs.cpp.s
.PHONY : src/bfs.cpp.s

src/bfs_opt.o: src/bfs_opt.cpp.o

.PHONY : src/bfs_opt.o

# target to build an object file
src/bfs_opt.cpp.o:
	$(MAKE) -f CMakeFiles/bfs_opt.dir/build.make CMakeFiles/bfs_opt.dir/src/bfs_opt.cpp.o
.PHONY : src/bfs_opt.cpp.o

src/bfs_opt.i: src/bfs_opt.cpp.i

.PHONY : src/bfs_opt.i

# target to preprocess a source file
src/bfs_opt.cpp.i:
	$(MAKE) -f CMakeFiles/bfs_opt.dir/build.make CMakeFiles/bfs_opt.dir/src/bfs_opt.cpp.i
.PHONY : src/bfs_opt.cpp.i

src/bfs_opt.s: src/bfs_opt.cpp.s

.PHONY : src/bfs_opt.s

# target to generate assembly for a file
src/bfs_opt.cpp.s:
	$(MAKE) -f CMakeFiles/bfs_opt.dir/build.make CMakeFiles/bfs_opt.dir/src/bfs_opt.cpp.s
.PHONY : src/bfs_opt.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... basic_class"
	@echo "... basic_lambda"
	@echo "... edit_cache"
	@echo "... A_star_algo_opt"
	@echo "... bfs"
	@echo "... bfs_opt"
	@echo "... basic_vector"
	@echo "... src/A_star_algo_opt.o"
	@echo "... src/A_star_algo_opt.i"
	@echo "... src/A_star_algo_opt.s"
	@echo "... src/basic_class.o"
	@echo "... src/basic_class.i"
	@echo "... src/basic_class.s"
	@echo "... src/basic_lambda.o"
	@echo "... src/basic_lambda.i"
	@echo "... src/basic_lambda.s"
	@echo "... src/basic_vector.o"
	@echo "... src/basic_vector.i"
	@echo "... src/basic_vector.s"
	@echo "... src/bfs.o"
	@echo "... src/bfs.i"
	@echo "... src/bfs.s"
	@echo "... src/bfs_opt.o"
	@echo "... src/bfs_opt.i"
	@echo "... src/bfs_opt.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

